---
title: "AltmetricExplorerAPI_ORCID_calls"
author: "Ana Macanovic"
date: "2023-12-13"
---

This script contains function that call the Altmetric Explorer API to obtain 
information based on an ORCID or a name of a researcher.

```{r include = F}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(eval = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

Load the libraries that we need:
```{r warning = F, message = F}
library(groundhog)
packages_to_load <- c("readr", "dplyr", 
                      "stringr",
                      "digest",
                      "jsonlite")
groundhog.library(packages_to_load, date = "2023-12-01")
```


Write a function that will get the filter for the ORCID and call the api:
```{r}
altmetric_api_orcid_caller <- function(orcid,
                                       api_secret,
                                       api_key,
                                       endpoint = c("research_outputs",
                                                    "attention",
                                                    "demographics",
                                                    "mentions",
                                                    "mention_sources",
                                                    "journals")){
  if (! endpoint %in% c("research_outputs",
                        "attention",
                        "demographics",
                        "mentions",
                        "mention_sources",
                        "journals")){
    stop('Please select one of the following endpoints: "research_outputs", "attention",
    "demographics", "mentions",  "mention_sources", "journals"')
  }
  
  filter_pt1 <- paste0('orcid|', orcid)
  filter_pt2 <- paste(filter_pt1, "scope|all", sep = "|")
  #filters = 'orcid|0000-0003-0800-5271|scope|all'
  digest <- hmac(api_secret, filter_pt2,
                 algo = c("sha1"),
                 serialize = FALSE)
  
  
  # build up the url by inserting an ORCID
  if (endpoint == "research_outputs"){
    url_pt1a <- paste0("https://www.altmetric.com/explorer/api/research_outputs?digest=", digest)
    url_pt1b <- paste0(url_pt1a, "&filter%5Borcid%5D=")
    url_pt1 <- paste0(url_pt1b, orcid)
  } else{
    # for other endpoints, specify the end point
    url_pt1a <- "https://www.altmetric.com/explorer/api/research_outputs/"
    url_pt1b <- paste0(paste0(url_pt1a, endpoint), "?digest=")
    url_pt1c <- paste0(url_pt1b, digest)
    url_pt1d <- paste0(url_pt1c, "&filter%5Borcid%5D=")
    url_pt1 <- paste0(url_pt1d, orcid)
  }
  # first, get the first page with a 100 results
  url_pt2 <- paste0(paste0("&filter%5Bscope%5D=all&key=", api_key), "&page%5Bnumber%5D=1")
  
  
  url_build <- paste0(url_pt1, url_pt2)
  
  # fetch the output
  output <- fromJSON(txt=url_build)
  
  # fetch the dataframe we need
  dataframe_output <- output$data
  
  # get the total number of results
  results_total <- output$meta$response$`total-results`
  # since we get results by a 100, get the number of calls we need (minus the one we made)
  calls_remaining <- ceiling(results_total/25)-1
  
  # if more calls remaining, call the api again, getting the correponding pages:
  for (call in seq_len(calls_remaining)){
    # build the url for each next page
    page <- call + 1
    url_pages <- paste0(paste0("&filter%5Bscope%5D=all&key=", api_key), "&page%5Bnumber%5D=")
    url_pages <- paste0(url_pages, page)
    url_build <- paste0(url_pt1, url_pages)
    page_output <- fromJSON(txt=url_build)
    dataframe_page_output <- page_output$data
    
    dataframe_output <- dataframe_output %>%
      dplyr::bind_rows(dataframe_page_output)
  }
  return(dataframe_output)
}
```

And then the one that calls the name:
```{r}
altmetric_api_name_caller <- function(name,
                                       api_secret,
                                       api_key,
                                       endpoint = c("research_outputs",
                                                    "attention",
                                                    "demographics",
                                                    "mentions",
                                                    "mention_sources",
                                                    "journals")){
  if (! endpoint %in% c("research_outputs",
                        "attention",
                        "demographics",
                        "mentions",
                        "mention_sources",
                        "journals")){
    stop('Please select one of the following endpoints: "research_outputs", "attention",
    "demographics", "mentions",  "mention_sources", "journals"')
  }
  
  filter_pt1 <- paste0('q|', name)
  digest <- hmac(api_secret, filter_pt1,
                 algo = c("sha1"),
                 serialize = FALSE)
  
  # build up the url by inserting an ORCID
  if (endpoint == "research_outputs"){
    url_pt1a <- paste0("https://www.altmetric.com/explorer/api/research_outputs?digest=", digest)
    url_pt1b <- paste0(url_pt1a, "&filter%5Bq%5D=")
    url_pt1 <- paste0(url_pt1b, str_replace(name, " ", "+"))
  } else{
    # for other endpoints, specify the end point
    url_pt1a <- "https://www.altmetric.com/explorer/api/research_outputs/"
    url_pt1b <- paste0(paste0(url_pt1a, endpoint), "?digest=")
    url_pt1c <- paste0(url_pt1b, digest)
    url_pt1d <- paste0(url_pt1c, "&filter%5Bq%5D=")
    url_pt1 <- paste0(url_pt1d, str_replace(name, " ", "+"))
  }
  # first, get the first page with a 100 results
  url_pt2 <- paste0(paste0("&key=", api_key), "&page%5Bnumber%5D=1")
  
  
  url_build <- paste0(url_pt1, url_pt2)
  
  # fetch the output
  output <- fromJSON(txt=url_build)
  
  # fetch the dataframe we need
  dataframe_output <- output$data
  
  # get the total number of results
  results_total <- output$meta$response$`total-results`
  # since we get results by a 100, get the number of calls we need (minus the one we made)
  calls_remaining <- ceiling(results_total/25)-1
  
  # if more calls remaining, call the api again, getting the correponding pages:
  for (call in seq_len(calls_remaining)){
    # build the url for each next page
    page <- call + 1
    url_pages <- paste0(paste0("&key=", api_key), "&page%5Bnumber%5D=")
    url_pages <- paste0(url_pages, page)
    url_build <- paste0(url_pt1, url_pages)
    page_output <- fromJSON(txt=url_build)
    dataframe_page_output <- page_output$data
    
    dataframe_output <- dataframe_output %>%
      dplyr::bind_rows(dataframe_page_output)
  }
  return(dataframe_output)
}
```


Test (get the key and secret key from https://www.altmetric.com/explorer/settings and assign them as the objects below):
```{r}
input_api_secret <- ''
input_api_key <- ''
orcid_test <- '0000-0002-9052-956X' 
name_test <- "bas hofstra"

test_output <- altmetric_api_orcid_caller(orcid = orcid_test,
                                          api_secret = input_api_secret,
                                          api_key = input_api_key,
                                          endpoint = "research_outputs")

test_attention <- altmetric_api_orcid_caller(orcid = orcid_test,
                                             api_secret = input_api_secret,
                                             api_key = input_api_key,
                                             endpoint = "attention")

test_name_output <- altmetric_api_name_caller(name = name_test,
                                            api_secret = input_api_secret,
                                            api_key = input_api_key,
                                            endpoint = "research_outputs")
```

