---
title: "Dutch media profs scripts"
output:
  html_document:
    toc: false
    number_sections: false
author: "by: Ana Macanovic and Bas Hofstra"
bibliography: references.bib

---


```{r, install remotely, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
# install.packages("remotes")
#remotes::install_github("rlesur/klippy")
``` 

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()

colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```


----

:::::::::::::: {.columns}
::: {.column width="80%"}

# Repository Description
Last compiled on `r format(Sys.time(), '%B, %Y')`  

This website shows the script for the Dutch Media Profs project.

It is still in progress.

<br>

Before beginning, make sure you install the groundhog package:
```{r eval = FALSE}
install.packages("groundhog")
```


----


:::
::: {.column width="80%"}


:::
::::::::::::::



## Contents

<br>

Use the top menu to navigate through the currently finished scripts.


----






